

INSERT INTO USERS(ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER)VALUES(USERS_SEQ.NEXTVAL, 'Parsa12345', '$2a$12$sTAGp30Jeb.3OKThy29TlOIEA3k90rh58JLLNz7Eg6IkdQl73bS.W', 'p.enayati@yahoo.com', '+98 9354821771');
INSERT INTO USERS(ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER)VALUES(USERS_SEQ.NEXTVAL, 'aa748', '$2a$12$oVo1JZhv1kdJGZ6NUU/XOOiE5AFrTUybtxRHTGmhKb9c4bDrtRkme', 'ahmadmoslem@yahoo.com', '+98 9903243639');
INSERT INTO USERS(ID, USER_NAME, PASSWORD, EMAIL, PHONE_NUMBER)VALUES(USERS_SEQ.NEXTVAL, 'Paaww21PP', '$$2a$12$N0E.wWZseQJfONCeamKi2O6mac7fxqkMjLaHdTL3nAQ/5gqNldAIu', 'ddd@1233@yahoo.com', '+98 9903229874');
SELECT * FROM USERS;

INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, USER_ID)VALUES(CUSTOMER_SEQ.NEXTVAL, 'Parsa', 'Enayati', null, 'Karaj. 3 Rahe Gohardasht. Meysam 6. Salamn Farsi 1.', 1);
INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ADDRESS, USER_ID)VALUES(CUSTOMER_SEQ.NEXTVAL, 'Mohsen', 'Sheikhi', 'Saber', 'Tehran. Marzdaran. Bosstan Seshom.', 2);
SELECT * FROM  CUSTOMER;

INSERT INTO RESTAURANT(ID, NAME, ADDRESS, USER_ID)VALUES(RESTAURANT_SEQ.NEXTVAL, 'Pizza Hot', 'Karaj. 3 Rahe Gohardasht. Falake Avval', 3);
SELECT * FROM RESTAURANT;


INSERT INTO MENU(ID, NAME, RESTAURANT_ID)VALUES(MENU_SEQ.NEXTVAL, 'Pizza', 1);
INSERT INTO MENU(ID, NAME, RESTAURANT_ID)VALUES(MENU_SEQ.NEXTVAL, 'Drink', 1);
SELECT * FROM MENU;



INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'پیتزای گوشت', 'خمیر پیتزا، پنیر موزاریلا، گوشت 70 درصد گوسفندی، قارچ و فلفل', 230000, 1);
INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'پیتزای مرغ', 'خمیر پیتزا، پنیر موزارلا، مرغ، سس قارچ، سس مخصوص', 256000, 1);
INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'پیتزای سبزیجات', 'خمیر پیتزا، گوجه و پنیر، نعنا، فلفل', 200000, 1);
INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'موهیتو', 'بدون توضیحات', 120000, 3);
INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'کوکا مشکی لیوانی', 'بدون توضیحات', 30000, 3);
INSERT INTO MENU_ITEM(ID, NAME, DESCRIPTION, PRICE, MENU_ID)VALUES(MENU_SEQ.NEXTVAL, 'رد دراگون', 'بدون توضیحات', 131000, 3);
SELECT * FROM MENU_ITEM;


INSERT INTO ORDERS(ID, STATUS, DESTINATION_ADDRESS, DATE_CREATED, RESTAURANT_ID, CUSTOMER_ID, REVIEW_ID)VALUES(ORDERS_SEQ.NEXTVAL, 'در انتظار تایید', 'Karaj. 3 Rahe Gohardasht. Meysam 6. Salamn Farsi 1.',  TO_DATE('2024-07-22 18:30:29', 'yyyy-mm-dd hh24:mi:ss'), 1, 1, null);
INSERT INTO ORDERS(ID, STATUS, DESTINATION_ADDRESS, DATE_CREATED, RESTAURANT_ID, CUSTOMER_ID, REVIEW_ID)VALUES(ORDERS_SEQ.NEXTVAL, 'اتمام سفارش', 'Tehran. Marzdaran. Bosstan Seshom.',  TO_DATE('2024-07-21 22:31:49', 'yyyy-mm-dd hh24:mi:ss'), 1, 2, null);
SELECT * FROM ORDERS;

INSERT INTO REVIEW(ID, TEXT, SCORE, ORDER_ID, DATE_SUBMIT)VALUES(REVIEW_SEQ.NEXTVAL, 'بسیار لذیذ و عالی همچنین نوشیدنی بسیار خنک به دستم رسید.', 9.8, 3,TO_DATE('2024-07-21 23:31:49', 'yyyy-mm-dd hh24:mi:ss'));
SELECT * FROM REVIEW;


INSERT INTO ORDER_ITEM(ID, COUNT, ORDER_ID, MENU_ITEM_ID)VALUES(ORDER_ITEM_SEQ.NEXTVAL, 3, 1, 4);
INSERT INTO ORDER_ITEM(ID, COUNT, ORDER_ID, MENU_ITEM_ID)VALUES(ORDER_ITEM_SEQ.NEXTVAL, 2, 1, 5);
INSERT INTO ORDER_ITEM(ID, COUNT, ORDER_ID, MENU_ITEM_ID)VALUES(ORDER_ITEM_SEQ.NEXTVAL, 5, 1, 17);
INSERT INTO ORDER_ITEM(ID, COUNT, ORDER_ID, MENU_ITEM_ID)VALUES(ORDER_ITEM_SEQ.NEXTVAL, 1, 3, 6);
SELECT * FROM ORDER_ITEM;



